name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    name: Main pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: psf/black@25.1.0
      - run: pip install -e .
